### ISSUE TITLE
I like the idea

### ISSUE THREAD

**Issue by TheBouwman** [FreedomOfRestriction/PyMaster#2]
I like the idea but I only but the only use want to use the tasks and punishment functions.

**Comment by FreedomOfRestriction** [comment]
The issue tracker is for bugs and suggestions, not reviews. Please keep this in mind next time.

If you want to just use the tasks and punishments, go ahead. Just create a master or mistress and ignore everything except requesting new tasks ("A chance to please my master/mistress") and admitting to wrongdoing. If this is insufficient, please create an issue indicating the exact feature you want. It might even already be there.
